### ISSUE TITLE
 Could not access itemWeight field at ModuleGrassSeeds.init line 80

### ISSUE THREAD

**Issue by Pfilson** [iguanaman/HungerOverhaul#13]
Crash log below.. 

Using 2l release, deleted config file to make sure it wasn't a config error. 
No Harvest Craft installed at this time (was fine without it before this release)
and using forge 9.11.1.953

Other mods are installed let me know if you want a list.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 12/12/13 4:34 PM
Description: Initializing game

java.lang.RuntimeException: Could not access itemWeight field, report please
    at iguanaman.hungeroverhaul.ModuleGrassSeeds.init(ModuleGrassSeeds.java:80)
    at iguanaman.hungeroverhaul.HungerOverhaul.postInit(HungerOverhaul.java:149)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:704)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at iguanaman.hungeroverhaul.ModuleGrassSeeds.init(ModuleGrassSeeds.java:80)
    at iguanaman.hungeroverhaul.HungerOverhaul.postInit(HungerOverhaul.java:149)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:545)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:201)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:181)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:112)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:704)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:249)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:509)

-- Initialization --
Details:
Stacktrace:
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:808)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:131)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:27)

-- System Details --
Details:
    Minecraft Version: 1.6.4
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 539580608 bytes (514 MB) / 889716736 bytes (848 MB) up to 1908932608 bytes (1820 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:PermSize=256m -XX:MaxPermSize=512m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.11 FML v6.4.45.953 Minecraft Forge 9.11.1.953 68 mods loaded, 68 mods active
    mcp{8.09} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    FML{6.4.45.953} [Forge Mod Loader](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forge{9.11.1.953} [Minecraft Forge](minecraftforge-9.11.1.953.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AppliedEnergistics-Core{rv14.finale2} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CodeChickenCore{0.9.0.6} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NotEnoughItems{1.6.1.5} [Not Enough Items](NotEnoughItems 1.6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    PowerCrystalsCore{1.1.8} [PowerCrystals Core](PowerCrystalsCore-1.1.8-9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TConstruct-Preloader{0.0.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    DamageIndicatorsMod{2.9.1.6} [Damage Indicators](1.6.4 DamageIndicatorsv2.9.1.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    bspkrsCore{v5.0(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev5.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ArmorStatusHUD{v1.15(1.6.4)} [ArmorStatusHUD]([1.6.4]ArmorStatusHUDv1.15.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_bspkrsCore{v5.0(1.6.4)} [bspkrsCore]([1.6.4]bspkrsCorev5.0.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    StatusEffectHUD{v1.19(1.6.4)} [StatusEffectHUD]([1.6.4]StatusEffectHUDv1.19.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    arsmagica2{1.0.2b} [Ars Magica 2](AM2_1.0.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AppliedEnergistics{rv14.finale2} [Applied Energistics](appeng-rv14-finale2-mc16x.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    barrels{3.2} [The Barrels Mod](Barrels 3.2-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Core{4.2.1} [BuildCraft](buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Builders{4.2.1} [BC Builders](buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Energy{4.2.1} [BC Energy](buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Factory{4.2.1} [BC Factory](buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Transport{4.2.1} [BC Transport](buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Silicon{4.2.1} [BC Silicon](buildcraft-A-1.6.4-4.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BurpTechCore{1.6.4.38} [BurpTech](burptech-1.6.4.38.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ChickenChunks{1.3.3.3} [ChickenChunks](ChickenChunks 1.3.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    EnderIO{0.5.1} [Ender IO](EnderIO-1.6.4-0.5.1.104.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    EnderStorage{1.4.3.5} [EnderStorage](EnderStorage 1.4.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    extracells{1.5.8b} [ExtraCells](ExtraCells-1.5.8b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded{1.6.2R2.7.3} [MineFactory Reloaded](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForestryPre{1.6.2R2.7.3} [MFR Compat: Forestry (part 2)](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forestry{2.3.0.7} [Forestry for Minecraft](forestry-A-2.3.0.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    GraveStone{2.4.6} [GraveStone](GraveStone_2.4.6.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Natura{2.1.12} [Natura](Natura_1.6.4_2.1.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ForgeMultipart{1.0.0.182} [Forge Multipart](ForgeMultipart-universal-1.6.4-1.0.0.182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TConstruct{1.6.X_1.5.1} [Tinkers' Construct](TConstruct_1.6.4_1.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Thaumcraft{4.0.5b} [Thaumcraft](Thaumcraft4.0.5b.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    HungerOverhaul{1.6.X-2l} [Hunger Overhaul](hungeroverhaul-1.6.X-2l-build1.zip) Unloaded->Constructed->Pre-initialized->Initialized->Errored
    MFR Compat Forestry Trees{1.0} [MFR Compat Forestry Trees](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MFR Compat Extra Trees{1.0} [MFR Compat Extra Trees](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.2R2.7.3} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatAtum{1.6.2R2.7.3} [MFR Compat: Atum](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatBackTools{1.6.2R2.7.3} [MFR Compat: BackTools](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatBuildCraft{1.6.2R2.7.3} [MFR Compat: BuildCraft](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatChococraft{1.6.2R2.7.3} [MFR Compat: Chococraft](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.6.2R2.7.3} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForestry{1.6.2R2.7.3} [MFR Compat: Forestry](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.6.2R2.7.3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatIC2{1.6.2R2.7.3} [MFR Compat: IC2](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatMagicalCrops{1.6.2R2.7.3} [MFR Compat: Magical Crops](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatMystcraft{1.6.2R2.7.3} [MFR Compat: Mystcraft](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatPams{1.6.2R2.7.3} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Railcraft{8.3.0.0} [Railcraft](Railcraft_1.6.4-8.3.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatRailcraft{1.6.2R2.7.3} [MFR Compat: Railcraft](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatRP2{1.6.2R2.7.3} [MFR Compat: RP2](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.6.2R2.7.3} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatThaumcraft{1.6.2R2.7.3} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.6.2R2.7.3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatTwilightForest{1.6.2R2.7.3} [MFR Compat: TwilightForest](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatVanilla{1.6.2R2.7.3} [MFR Compat: Vanilla](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatXyCraft{1.6.2R2.7.3} [MFR Compat: XyCraft](MineFactoryReloaded-2.7.3-179.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    QuantumCraft{1.02_mc164} [qCraft](qCraft1.02_mc164.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TMechworks{DEV.21b1027} [Tinkers' Mechworks](TMechworks_1.6.4_0.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Translocator{1.1.0.13} [Translocator](Translocator 1.1.0.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    WR-CBE|Core{1.4.0.6} [WR-CBE Core](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    WR-CBE|Addons{1.4.0.6} [WR-CBE Addons](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    WR-CBE|Logic{1.4.0.6} [WR-CBE Logic](WR-CBE 1.4.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    mod_ZanMinimap{0.9.4} [Zan's Minimap](ZansMinimap1.6.4.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    McMultipart{1.0.0.182} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.4-1.0.0.182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ForgeMicroblock{1.0.0.182} [Forge Microblocks](ForgeMultipart-universal-1.6.4-1.0.0.182.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TConstruct Environment: Sane and ready for action. Bugs may be reported.
    Launched Version: 1.6.4-Forge9.11.1.953
    LWJGL: 2.9.0
    OpenGL: Intel(R) HD Graphics 3000 GL version 3.1.0 - Build 9.17.10.2843, Intel
    Is Modded: Definitely; Client brand changed to 'fml,forge'
    Type: Client (map_client.txt)
    Resource Pack: Default
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: ~~ERROR~~ NullPointerException: null

**Comment by iguanaman** [comment]
Thanks for reporting so promptly (though in future, please use pastebin when posting crashlogs), fixed now in latest release.

**Comment by Pfilson** [comment]
No problem, I just happened to be checking for updates right after you put the new one up.  And sorry about that I'll make sure to do that next time.
